#!/usr/bin/env bash
#a Bash script that pings an IP address passed as an argument.

# Check if an IP address argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
