#!/usr/bin/env bash
# a Bash script that displays:

#+ a sleep 2 in between each iteration.
#   Displays "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done

