#!/usr/bin/env bash
#a Bash script that displays Best School 10 times, but for the 9th it, follows with Hi.

count=0

while [ $count -lt 10 ];
do
if [ $count -eq 8 ];
then
echo "Best School"
echo  "Hi"
else
echo "Best School"
fi
count=$((count + 1))
done
