#!/usr/bin/env bash
#a Bash script that displays the time for 12 hours and 59 minutes:

hour=0
minute=1
count=1

while [ $count -le 70 ]; do
    printf "%02d:%02d\n" $hour $minute
    
    minute=$((minute + 1))

    if [ $minute -eq 60 ]; then
        minute=0
        hour=$((hour + 1))
    fi

    if [ $hour -eq 13 ]; then
        hour=0
    fi

    count=$((count + 1))
done | head -n 70
